<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Demo" duration-ms="15530" started-at="2016-03-07T19:29:41Z" finished-at="2016-03-07T19:29:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="15530" started-at="2016-03-07T19:29:41Z" finished-at="2016-03-07T19:29:57Z">
      <class name="com.ahabana.Main">
        <test-method status="PASS" signature="test(java.lang.String)[pri:0, instance:com.ahabana.Main@5b799640]" name="test" duration-ms="9178" started-at="2016-03-07T11:29:41Z" data-provider="getData" finished-at="2016-03-07T11:29:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[92003]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(java.lang.String)[pri:0, instance:com.ahabana.Main@5b799640]" name="test" duration-ms="6336" started-at="2016-03-07T11:29:51Z" data-provider="getData" finished-at="2016-03-07T11:29:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[75555]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.ahabana.Browser.validateCamry(Browser.java:82)
	at com.ahabana.Main.test(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.TestNG.privateMain(TestNG.java:1385)
	at org.testng.TestNG.main(TestNG.java:1354)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.ahabana.Main@5b799640]" name="afterTest" is-config="true" duration-ms="6" started-at="2016-03-07T11:29:57Z" finished-at="2016-03-07T11:29:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.ahabana.Main -->
    </test> <!-- Test -->
  </suite> <!-- Demo -->
</testng-results>
